// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ReportScheduler
{
    public partial class CompanyReport
    {
        public CompanyReport()
        {
            CompanyReportColumnConfiguration = new HashSet<CompanyReportColumnConfiguration>();
            CompanyReportFilterConfiguration = new HashSet<CompanyReportFilterConfiguration>();
        }

        public int Id { get; set; }
        public int ReportDataSetId { get; set; }
        public int CompanyId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsSchedule { get; set; }
        public int? ScheduleDay { get; set; }
        public DateTime? ScheduleTime { get; set; }
        public bool? IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public byte[] Version { get; set; }

        public virtual ReportDataSet ReportDataSet { get; set; }
        public virtual ICollection<CompanyReportColumnConfiguration> CompanyReportColumnConfiguration { get; set; }
        public virtual ICollection<CompanyReportFilterConfiguration> CompanyReportFilterConfiguration { get; set; }
    }
}