// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ReportScheduler
{
    public partial class ReportDataSet
    {
        public ReportDataSet()
        {
            CompanyReport = new HashSet<CompanyReport>();
            ReportColumn = new HashSet<ReportColumn>();
            ReportFilter = new HashSet<ReportFilter>();
        }

        public int Id { get; set; }
        public string DisplayName { get; set; }
        public string Name { get; set; }

        public virtual ICollection<CompanyReport> CompanyReport { get; set; }
        public virtual ICollection<ReportColumn> ReportColumn { get; set; }
        public virtual ICollection<ReportFilter> ReportFilter { get; set; }
    }
}