// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ReportScheduler
{
    public partial class ReportFilter
    {
        public ReportFilter()
        {
            CompanyReportFilterConfiguration = new HashSet<CompanyReportFilterConfiguration>();
        }

        public int Id { get; set; }
        public int ReportDataSetId { get; set; }
        public string DisplayName { get; set; }
        public string Name { get; set; }

        public virtual ReportDataSet ReportDataSet { get; set; }
        public virtual ICollection<CompanyReportFilterConfiguration> CompanyReportFilterConfiguration { get; set; }
    }
}